env:
 - GHCVER=7.8.2

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update
 - sudo apt-get install cabal-install-1.20 ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:$PATH
 - |
   if [ $GHCVER = "head" ] || [ ${GHCVER%.*} = "7.8" ]; then
     sudo apt-get install happy-1.19.4 alex-3.1.3
     export PATH=/opt/alex/3.1.3/bin:/opt/happy/1.19.4/bin:$PATH
   else
     sudo apt-get install happy alex
   fi

install:
 - cabal-1.20 update
 - cabal-1.20 sandbox init
 - cabal-1.20 install --only-dependencies

script:
 - cabal-1.20 configure --enable-tests -v2
 - cabal-1.20 build
 - cabal-1.20 test
